export const TIMEZONE_OPTIONS: ReadonlyArray<{ timezone: string; label: string }> = [
  { timezone: 'America/New_York', label: 'New York' },
  { timezone: 'America/Chicago', label: 'Chicago' },
  { timezone: 'America/Denver', label: 'Denver' },
  { timezone: 'America/Los_Angeles', label: 'Los Angeles' },
  { timezone: 'America/Anchorage', label: 'Anchorage' },
  { timezone: 'Pacific/Honolulu', label: 'Honolulu' },
  { timezone: 'America/Toronto', label: 'Toronto' },
  { timezone: 'America/Vancouver', label: 'Vancouver' },
  { timezone: 'America/Mexico_City', label: 'Mexico City' },
  { timezone: 'America/Sao_Paulo', label: 'S\u00e3o Paulo' },
  { timezone: 'America/Buenos_Aires', label: 'Buenos Aires' },
  { timezone: 'America/Bogota', label: 'Bogot\u00e1' },
  { timezone: 'America/Lima', label: 'Lima' },
  { timezone: 'Europe/London', label: 'London' },
  { timezone: 'Europe/Paris', label: 'Paris' },
  { timezone: 'Europe/Berlin', label: 'Berlin' },
  { timezone: 'Europe/Madrid', label: 'Madrid' },
  { timezone: 'Europe/Rome', label: 'Rome' },
  { timezone: 'Europe/Amsterdam', label: 'Amsterdam' },
  { timezone: 'Europe/Zurich', label: 'Zurich' },
  { timezone: 'Europe/Vienna', label: 'Vienna' },
  { timezone: 'Europe/Stockholm', label: 'Stockholm' },
  { timezone: 'Europe/Oslo', label: 'Oslo' },
  { timezone: 'Europe/Copenhagen', label: 'Copenhagen' },
  { timezone: 'Europe/Helsinki', label: 'Helsinki' },
  { timezone: 'Europe/Warsaw', label: 'Warsaw' },
  { timezone: 'Europe/Prague', label: 'Prague' },
  { timezone: 'Europe/Athens', label: 'Athens' },
  { timezone: 'Europe/Istanbul', label: 'Istanbul' },
  { timezone: 'Europe/Moscow', label: 'Moscow' },
  { timezone: 'Africa/Cairo', label: 'Cairo' },
  { timezone: 'Africa/Lagos', label: 'Lagos' },
  { timezone: 'Africa/Johannesburg', label: 'Johannesburg' },
  { timezone: 'Africa/Nairobi', label: 'Nairobi' },
  { timezone: 'Asia/Dubai', label: 'Dubai' },
  { timezone: 'Asia/Karachi', label: 'Karachi' },
  { timezone: 'Asia/Kolkata', label: 'Mumbai' },
  { timezone: 'Asia/Dhaka', label: 'Dhaka' },
  { timezone: 'Asia/Bangkok', label: 'Bangkok' },
  { timezone: 'Asia/Singapore', label: 'Singapore' },
  { timezone: 'Asia/Hong_Kong', label: 'Hong Kong' },
  { timezone: 'Asia/Shanghai', label: 'Shanghai' },
  { timezone: 'Asia/Taipei', label: 'Taipei' },
  { timezone: 'Asia/Seoul', label: 'Seoul' },
  { timezone: 'Asia/Tokyo', label: 'Tokyo' },
  { timezone: 'Australia/Perth', label: 'Perth' },
  { timezone: 'Australia/Sydney', label: 'Sydney' },
  { timezone: 'Australia/Melbourne', label: 'Melbourne' },
  { timezone: 'Pacific/Auckland', label: 'Auckland' },
  { timezone: 'Pacific/Fiji', label: 'Fiji' },
];
